//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elibrium.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElibriumEntities : DbContext
    {
        public ElibriumEntities()
            : base("name=ElibriumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<PersonEmailTemplate> PersonEmailTemplate { get; set; }
        public virtual DbSet<ContactType> ContactType { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplate { get; set; }
        public virtual DbSet<Hobby> Hobby { get; set; }
        public virtual DbSet<Offer> Offer { get; set; }
        public virtual DbSet<PersonOffer> PersonOffer { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<PositionType> PositionType { get; set; }
    }
}
