//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elibrium.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonOffer
    {
        public int Id { get; set; }
        public int OfferId { get; set; }
        public int PersonId { get; set; }
        public string Status { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Offer Offer { get; set; }
    }
}
